source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.6'

gem 'bootsnap'
gem 'jbuilder'
gem 'pg'
gem 'puma'
gem 'rails'
gem 'redis'
gem 'sass-rails'
gem 'turbolinks'
gem 'webpacker'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'faker'
  gem 'listen'
  gem 'rspec-core'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
  gem 'rspec-rails'
  gem 'rspec-support'
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'web-console'
end
